version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gosec
    - gocyclo
    - govet
    - ineffassign
    - revive
    - misspell
    - nakedret
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
